-- =============================================================================
-- Pawtal CMS — Initial Schema
-- =============================================================================
-- Conventions used throughout this file:
--   • Primary keys are random 16-byte hex strings generated by SQLite so the
--     application never has to generate IDs out-of-band.
--   • Timestamps are stored as ISO-8601 UTC strings
--     (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')) for portability.
--   • TEXT CHECK constraints encode enum-like fields at the DB layer so
--     invalid values are rejected even if the application layer has a bug.
--   • Foreign key CASCADE rules make child-row cleanup automatic and safe.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id           TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    -- Opaque identifier from the OAuth2 provider (Authentik subject claim).
    external_id  TEXT    NOT NULL UNIQUE,
    email        TEXT    NOT NULL,
    display_name TEXT    NOT NULL,
    role         TEXT    NOT NULL CHECK (role IN ('admin', 'editor')),
    created_at   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    last_login   TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
    id         TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    user_id    TEXT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token      TEXT    NOT NULL UNIQUE,
    expires_at TEXT    NOT NULL,
    created_at TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX sessions_token_idx      ON sessions (token);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- Site settings (key/value store)
-- ---------------------------------------------------------------------------
CREATE TABLE site_settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

INSERT INTO site_settings (key, value) VALUES
    ('site_title',          'Pawtal'),
    ('front_page_type',     'articles'),
    ('front_page_id',       ''),
    ('apps_per_page',       '12'),
    ('app_catalogue_intro', ''),
    ('dark_mode_default',   'false');

-- ---------------------------------------------------------------------------
-- Categories (shared by pages and articles)
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id   TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- Pages
-- ---------------------------------------------------------------------------
CREATE TABLE pages (
    id         TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    title      TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    content    TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft', 'published', 'scheduled', 'trashed')),
    publish_at TEXT,   -- NULL means publish immediately when status → published
    author_id  TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    trashed_at TEXT     -- populated when status = 'trashed'
);

CREATE INDEX pages_slug_idx   ON pages (slug);
CREATE INDEX pages_status_idx ON pages (status);

-- ---------------------------------------------------------------------------
-- Page revisions
-- ---------------------------------------------------------------------------
CREATE TABLE page_revisions (
    id        TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    page_id   TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
    title     TEXT NOT NULL,
    content   TEXT NOT NULL DEFAULT '',
    author_id TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX page_revisions_page_id_idx ON page_revisions (page_id);

-- ---------------------------------------------------------------------------
-- Page ↔ category join table
-- ---------------------------------------------------------------------------
CREATE TABLE page_categories (
    page_id     TEXT NOT NULL REFERENCES pages(id)      ON DELETE CASCADE,
    category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (page_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Articles
-- ---------------------------------------------------------------------------
CREATE TABLE articles (
    id         TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    title      TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    short_text TEXT NOT NULL DEFAULT '',
    content    TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT 'draft'
                   CHECK (status IN ('draft', 'published', 'scheduled', 'trashed')),
    publish_at TEXT,
    author_id  TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    trashed_at TEXT
);

CREATE INDEX articles_slug_idx   ON articles (slug);
CREATE INDEX articles_status_idx ON articles (status);

-- ---------------------------------------------------------------------------
-- Article revisions
-- ---------------------------------------------------------------------------
CREATE TABLE article_revisions (
    id         TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    article_id TEXT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    title      TEXT NOT NULL,
    short_text TEXT NOT NULL DEFAULT '',
    content    TEXT NOT NULL DEFAULT '',
    author_id  TEXT NOT NULL REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX article_revisions_article_id_idx ON article_revisions (article_id);

-- ---------------------------------------------------------------------------
-- Article ↔ category join table
-- ---------------------------------------------------------------------------
CREATE TABLE article_categories (
    article_id  TEXT NOT NULL REFERENCES articles(id)    ON DELETE CASCADE,
    category_id TEXT NOT NULL REFERENCES categories(id)  ON DELETE CASCADE,
    PRIMARY KEY (article_id, category_id)
);

-- ---------------------------------------------------------------------------
-- Media
-- ---------------------------------------------------------------------------
CREATE TABLE media (
    id                TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    filename          TEXT    NOT NULL,   -- stored filename on disk
    original_filename TEXT    NOT NULL,   -- name at upload time
    mime_type         TEXT    NOT NULL,
    size_bytes        INTEGER NOT NULL,
    width             INTEGER,            -- NULL for non-image files
    height            INTEGER,
    alt_text          TEXT    NOT NULL DEFAULT '',
    is_icon           INTEGER NOT NULL DEFAULT 0,  -- boolean: 1 = icon, 0 = general media
    uploaded_by       TEXT    NOT NULL REFERENCES users(id),
    created_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- Apps (app catalogue entries)
-- ---------------------------------------------------------------------------
CREATE TABLE apps (
    id          TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name        TEXT    NOT NULL,
    description TEXT    NOT NULL DEFAULT '',
    -- Optional icon from the media library; NULL if no icon set.
    icon_id     TEXT    REFERENCES media(id) ON DELETE SET NULL,
    url         TEXT,   -- external URL, NULL if the app uses an internal page
    -- Optional link to an internal page for more details.
    page_id     TEXT    REFERENCES pages(id) ON DELETE SET NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- Menus
-- ---------------------------------------------------------------------------
CREATE TABLE menus (
    id   TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    name TEXT NOT NULL UNIQUE
);

-- Seed the two standard menus so application code can reference them by name
-- without needing a setup step.
INSERT INTO menus (name) VALUES ('main'), ('footer');

-- ---------------------------------------------------------------------------
-- Menu items
-- ---------------------------------------------------------------------------
CREATE TABLE menu_items (
    id          TEXT    PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    menu_id     TEXT    NOT NULL REFERENCES menus(id) ON DELETE CASCADE,
    label       TEXT    NOT NULL,
    link_type   TEXT    NOT NULL
                        CHECK (link_type IN ('page', 'article', 'url', 'app_catalogue')),
    link_target TEXT    NOT NULL DEFAULT '',  -- page/article id, URL, or empty for app_catalogue
    -- Self-referential FK for nested menus; NULL = top-level item.
    parent_id   TEXT    REFERENCES menu_items(id) ON DELETE CASCADE,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX menu_items_menu_id_idx ON menu_items (menu_id);

-- ---------------------------------------------------------------------------
-- Audit log
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
    user_id     TEXT NOT NULL REFERENCES users(id),
    action      TEXT NOT NULL,        -- e.g. 'create', 'update', 'delete', 'publish'
    entity_type TEXT NOT NULL,        -- e.g. 'article', 'page', 'media'
    entity_id   TEXT NOT NULL,
    -- Structured JSON payload with before/after snapshots or other context.
    details     TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE INDEX audit_log_created_at_idx            ON audit_log (created_at);
CREATE INDEX audit_log_entity_type_entity_id_idx ON audit_log (entity_type, entity_id);

-- =============================================================================
-- Full-Text Search (FTS5)
-- =============================================================================
-- FTS5 "content" tables keep the index in sync with the source table via
-- triggers below. The index itself stores no content — queries join back to
-- the source table for the actual data (saves storage, avoids duplication).

CREATE VIRTUAL TABLE pages_fts USING fts5(
    title,
    content,
    content=pages,
    content_rowid=rowid
);

CREATE VIRTUAL TABLE articles_fts USING fts5(
    title,
    short_text,
    content,
    content=articles,
    content_rowid=rowid
);

CREATE VIRTUAL TABLE apps_fts USING fts5(
    name,
    description,
    content=apps,
    content_rowid=rowid
);

-- =============================================================================
-- FTS Triggers — keep search indexes in sync with source tables
-- =============================================================================

-- ----- pages ----------------------------------------------------------------
CREATE TRIGGER pages_fts_insert AFTER INSERT ON pages BEGIN
    INSERT INTO pages_fts (rowid, title, content)
    VALUES (new.rowid, new.title, new.content);
END;

CREATE TRIGGER pages_fts_delete AFTER DELETE ON pages BEGIN
    INSERT INTO pages_fts (pages_fts, rowid, title, content)
    VALUES ('delete', old.rowid, old.title, old.content);
END;

CREATE TRIGGER pages_fts_update AFTER UPDATE ON pages BEGIN
    INSERT INTO pages_fts (pages_fts, rowid, title, content)
    VALUES ('delete', old.rowid, old.title, old.content);
    INSERT INTO pages_fts (rowid, title, content)
    VALUES (new.rowid, new.title, new.content);
END;

-- ----- articles -------------------------------------------------------------
CREATE TRIGGER articles_fts_insert AFTER INSERT ON articles BEGIN
    INSERT INTO articles_fts (rowid, title, short_text, content)
    VALUES (new.rowid, new.title, new.short_text, new.content);
END;

CREATE TRIGGER articles_fts_delete AFTER DELETE ON articles BEGIN
    INSERT INTO articles_fts (articles_fts, rowid, title, short_text, content)
    VALUES ('delete', old.rowid, old.title, old.short_text, old.content);
END;

CREATE TRIGGER articles_fts_update AFTER UPDATE ON articles BEGIN
    INSERT INTO articles_fts (articles_fts, rowid, title, short_text, content)
    VALUES ('delete', old.rowid, old.title, old.short_text, old.content);
    INSERT INTO articles_fts (rowid, title, short_text, content)
    VALUES (new.rowid, new.title, new.short_text, new.content);
END;

-- ----- apps -----------------------------------------------------------------
CREATE TRIGGER apps_fts_insert AFTER INSERT ON apps BEGIN
    INSERT INTO apps_fts (rowid, name, description)
    VALUES (new.rowid, new.name, new.description);
END;

CREATE TRIGGER apps_fts_delete AFTER DELETE ON apps BEGIN
    INSERT INTO apps_fts (apps_fts, rowid, name, description)
    VALUES ('delete', old.rowid, old.name, old.description);
END;

CREATE TRIGGER apps_fts_update AFTER UPDATE ON apps BEGIN
    INSERT INTO apps_fts (apps_fts, rowid, name, description)
    VALUES ('delete', old.rowid, old.name, old.description);
    INSERT INTO apps_fts (rowid, name, description)
    VALUES (new.rowid, new.name, new.description);
END;
